<a href="https://colab.research.google.com/github/kailashchaudhary-p/Daily-Expense-Analyzer/blob/main/Daily_Expense_Analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd
import numpy as np
try:
  df=pd.read_csv("/content/Transactions.csv")
  print(f"data set load succesfully . shape :{df.shape}")
except Exception as e:
  print(f"Error loading the data set : {e}")
df.head()

data set load succesfully . shape :(2461, 8)

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
0,20/09/2018 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR
1,20/09/2018 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR
2,19/09/2018,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
4,16/09/2018 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR

In [22]:
df.tail()

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
2456,1/1/2015,Cash,Transportation,NaN,share jeep - Place T base to top,20.0,Expense,INR
2457,1/1/2015,Cash,Transportation,NaN,share auto - Place H to Place T base,20.0,Expense,INR
2458,1/1/2015,Cash,Transportation,NaN,bus - brc to Place H,30.0,Expense,INR
2459,1/1/2015,Cash,Food,NaN,tea,10.0,Expense,INR
2460,1/1/2015,Cash,Transportation,NaN,share auto - hospital to brc station,10.0,Expense,INR

In [23]:
df.columns

Index(['Date', 'Mode', 'Category', 'Subcategory', 'Note', 'Amount',
       'Income/Expense', 'Currency'],
      dtype='object')

In [24]:
df.isnull().sum()

Date                0
Mode                0
Category            0
Subcategory       635
Note              521
Amount              0
Income/Expense      0
Currency            0
dtype: int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2461 entries, 0 to 2460
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2461 non-null   object
 1   Mode            2461 non-null   object
 2   Category        2461 non-null   object
 3   Subcategory     1826 non-null   object
 4   Note            1940 non-null   object
 5   Amount          2461 non-null   float64
 6   Income/Expense  2461 non-null   object
 7   Currency        2461 non-null   object
dtypes: float64(1), object(7)
memory usage: 153.9+ KB

In [26]:
df["Mode"].unique()

array(['Cash', 'Saving Bank account 1', 'Credit Card',
       'Equity Mutual Fund B', 'Debit Card', 'Share Market Trading',
       'Saving Bank account 2', 'Equity Mutual Fund C',
       'Equity Mutual Fund A', 'Equity Mutual Fund D', 'Fixed Deposit',
       'Recurring Deposit'], dtype=object)

In [27]:
df['Category'].unique()

array(['Transportation', 'Food', 'subscription', 'Festivals', 'Other',
       'Small Cap fund 2', 'Small cap fund 1', 'Family',
       'Equity Mutual Fund E', 'Apparel', 'Public Provident Fund',
       'Saving Bank account 1', 'Gift', 'Salary', 'Household',
       'Dividend earned on Shares', 'Interest', 'Life Insurance',
       'Beauty', 'Health', 'Money transfer', 'maid', 'Culture',
       'Tax refund', 'Tourism', 'Share Market', 'Self-development',
       'Amazon pay cashback', 'Education', 'scrap', 'Petty cash',
       'Documents', 'Gpay Reward', 'Social Life', 'Equity Mutual Fund A',
       'Maturity amount', 'Fixed Deposit', 'Equity Mutual Fund C',
       'Equity Mutual Fund F', 'Recurring Deposit',
       'Saving Bank account 2', 'Equity Mutual Fund D',
       'Equity Mutual Fund B', 'Bonus', 'Investment', 'Grooming', 'Rent',
       'Cook', 'garbage disposal', 'water (jar /tanker)'], dtype=object)

In [28]:
df['Income/Expense'].unique()

array(['Expense', 'Transfer-Out', 'Income'], dtype=object)

In [29]:
df.duplicated().sum()

np.int64(9)

In [30]:
expense_df = df[df['Income/Expense']=='Expense']

In [31]:
expense_df.shape

(2176, 8)

In [32]:
expense_df.head(10)

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
0,20/09/2018 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR
1,20/09/2018 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR
2,19/09/2018,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
4,16/09/2018 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR
5,15/09/2018 06:34:17,Credit Card,subscription,Tata Sky,Permanent Residence - Tata Play recharge,200.0,Expense,INR
6,14/09/2018 05:39:17,Cash,Transportation,auto,Place 2 station to Permanent Residence,50.0,Expense,INR
7,13/09/2018 21:35:15,Saving Bank account 1,Transportation,Train,2 Place 0 to Place 3,40.0,Expense,INR
8,13/09/2018 21:01:47,Credit Card,Other,NaN,HBR 2 Months subscription,83.0,Expense,INR
9,13/09/2018 21:01:32,Cash,Food,Grocery,1kg atta,46.0,Expense,INR

In [33]:
len(expense_df)

2176

In [34]:
expense_df['Category'].value_counts()

Category
Food                     907
Transportation           307
Household                176
subscription             143
Other                    114
Investment               103
Health                    94
Family                    71
Apparel                   47
Money transfer            43
Gift                      30
Recurring Deposit         22
Beauty                    22
Education                 18
maid                      17
Festivals                 16
Culture                   11
Public Provident Fund      8
Tourism                    5
Rent                       4
Cook                       4
Grooming                   4
water (jar /tanker)        3
Self-development           2
Documents                  2
garbage disposal           2
Social Life                1
Name: count, dtype: int64

In [35]:
expense_df['Mode'].value_counts()

Mode
Cash                     1039
Saving Bank account 1     971
Credit Card               162
Debit Card                  2
Saving Bank account 2       2
Name: count, dtype: int64

In [36]:
expense_df.isnull().sum()

Date                0
Mode                0
Category            0
Subcategory       350
Note              346
Amount              0
Income/Expense      0
Currency            0
dtype: int64

In [37]:
expense_df [expense_df['Category'] == 'Investment'].head(10)

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
1751,10/12/2016,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,INR
1756,7/12/2016,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,INR
1758,5/12/2016,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,INR
1772,1/12/2016,Saving Bank account 1,Investment,Public Provident Fund,NaN,40000.0,Expense,INR
1813,10/11/2016,Saving Bank account 1,Investment,RD,RD,1000.0,Expense,INR
1814,10/11/2016,Saving Bank account 1,Investment,LIC,Life Insurance,11286.0,Expense,INR
1815,10/11/2016,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,INR
1816,10/11/2016,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,INR
1821,5/11/2016,Saving Bank account 1,Investment,RD,RD,1000.0,Expense,INR
1822,5/11/2016,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,INR

In [38]:
expense_df.isnull().sum()

Date                0
Mode                0
Category            0
Subcategory       350
Note              346
Amount              0
Income/Expense      0
Currency            0
dtype: int64

In [40]:
expense_df['Subcategory'] = expense_df['Subcategory'].fillna('Unknown')

/tmp/ipykernel_1294/1614961070.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  expense_df['Subcategory'] = expense_df['Subcategory'].fillna('Unknown')

In [42]:
expense_df['Note'] = expense_df['Note'].fillna('No Note')

/tmp/ipykernel_1294/425735231.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  expense_df['Note'] = expense_df['Note'].fillna('No Note')

In [43]:
expense_df.head(10)

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
0,20/09/2018 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR
1,20/09/2018 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR
2,19/09/2018,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
4,16/09/2018 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR
5,15/09/2018 06:34:17,Credit Card,subscription,Tata Sky,Permanent Residence - Tata Play recharge,200.0,Expense,INR
6,14/09/2018 05:39:17,Cash,Transportation,auto,Place 2 station to Permanent Residence,50.0,Expense,INR
7,13/09/2018 21:35:15,Saving Bank account 1,Transportation,Train,2 Place 0 to Place 3,40.0,Expense,INR
8,13/09/2018 21:01:47,Credit Card,Other,Unknown,HBR 2 Months subscription,83.0,Expense,INR
9,13/09/2018 21:01:32,Cash,Food,Grocery,1kg atta,46.0,Expense,INR

In [44]:
expense_df.isnull().sum()

Date              0
Mode              0
Category          0
Subcategory       0
Note              0
Amount            0
Income/Expense    0
Currency          0
dtype: int64